server:
  port: 80
spring:
  application:
    name: consumer-cloud
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

ribbon:  #设置feign client 超时时间 默认支持 Ribbon
  ReadTimeout: 6000 #建立连接所用的时间，适用于网络状况正常的情况下，两端两端连接所用的时间
  ConnectionTimeout: 6000 #建立连接后，服务器读取到可用资源的时间

logging:
  level:
    #feign 日志以什么样的级别监控该接口
    com.consumer.service.ProviderFeign: debug