server:
  port: 9527

spring:
  application:
    name: gateway-cloud
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway: #网关路由配置
      discovery:
        locator:
          enabled: true #默认值为 true，即默认开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        #将 cloud_provider_routh-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
        - id: cloud_provider_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://bzy-server #动态路由，使用服务名代替上面的具体带端口   http://localhost:8001
          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/provider/**    #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET #只能时 GET 请求时，才能访问